Repository Kuadrant/multicluster-gateway-controller, pull requests merged in 2023-05, with the labels that each got.

#177 Remove build-agent make target
  Makefile
Labels: approved, lgtm

#187 rough fix for downstream ns being different than upstream
  docs/ocm-control-plane-walkthrough.md
  pkg/controllers/gateway/gateway_controller.go
  pkg/placement/ocm.go
Labels: approved

#188 adding istio to single cluster arch
  hack/local-setup.sh
Labels: approved, lgtm

#191 Fixes
  docs/ocm-control-plane-walkthrough.md
  hack/local-setup.sh
  pkg/controllers/gateway/gateway_controller.go
  pkg/placement/ocm.go
Labels: approved, lgtm

#195 Clusteradm path
  README.md
  hack/local-setup.sh
Labels: lgtm

#194 walkthrough update
  docs/ocm-control-plane-walkthrough.md
Labels: approved

#169 #105: Implement DNS Health Check reconciliation
  cmd/controller/main.go
  config/crd/bases/kuadrant.io_dnspolicies.yaml
  config/rbac/role.yaml
  config/samples/dnspolicy.yaml
  go.mod
  go.sum
  pkg/_internal/slice/slice.go
  pkg/apis/v1alpha1/dnspolicy_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/dnspolicy/dnsrecord_eventhandler.go
  pkg/controllers/dnspolicy/health.go
  pkg/controllers/dnspolicy/util.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/gateway/suite_test.go
  pkg/controllers/ratelimitpolicy/ratelimitpolicy_controller.go
  pkg/dns/aws/aws_test.go
  pkg/dns/aws/dns.go
  pkg/dns/aws/health.go
  pkg/dns/aws/health_test.go
  pkg/dns/dns.go
  pkg/dns/health.go
  pkg/dns/service.go
Labels: approved, lgtm

#162 Gh 117 Cert and DNRecord deletion
  config/rbac/role.yaml
  pkg/controllers/dnsrecord/dnsrecord_controller.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/ratelimitpolicy/ratelimitpolicy_controller.go
  pkg/dns/service.go
  pkg/tls/service.go
Labels: approved, lgtm

#207 #101 Wait for dashboard deployment
  hack/local-setup.sh
Labels: approved, lgtm

#208 fix event handler tests
  pkg/controllers/gateway/cluster_eventhandler.go
  pkg/controllers/gateway/cluster_eventhandler_test.go
Labels: approved

#209 add crds
  config/ocm/crd/cluster.yaml
  config/ocm/crd/placement.yaml
  config/ocm/crd/placementdecision.yaml
  config/ocm/crd/work.yaml
Labels: approved

#212 add back missing aws validation
  pkg/dns/aws/dns.go
Labels: approved

#216 fix reference to gateway to ensure deletion of dns and certs
  pkg/controllers/gateway/gateway_controller.go
Labels: approved, lgtm

#217 Fix local-setup on linux
  hack/local-setup.sh
Labels: approved, lgtm

#224 Pin clusteradm to 0.5.1 release and ocm bundle to 0.10.0
  hack/local-setup.sh
  hack/make/dependencies.make
Labels: approved, lgtm

#223 Remove rlp controller
  PROJECT
  cmd/controller/main.go
  config/kuadrant/crd/kuadrant.io.ratelimitpolicies.yaml
  config/kuadrant/crd/kustomization.yaml
  config/rbac/role.yaml
  config/samples/ratelimitpolicy.yaml
  config/syncer/syncer.yaml
  docs/milestone2/milestone2_application.yaml
  docs/milestone2/milestone2_gateway.yaml
  docs/milestone2/milestone2_ratelimitpolicy.yaml
  docs/milestone2/milestone2_walkthrough.md
  docs/milestone2/status_aggregation.md
  docs/ratelimitpolicy/walkthrough/echo-application.yaml
  docs/ratelimitpolicy/walkthrough/gateway.yaml
  docs/ratelimitpolicy/walkthrough/gatewayclass.yaml
  docs/ratelimitpolicy/walkthrough/ratelimitpolicy-cluster_attr_limit.yaml
  docs/ratelimitpolicy/walkthrough/ratelimitpolicy-custom_attr_limit.yaml
  docs/ratelimitpolicy/walkthrough/ratelimitpolicy.yaml
  docs/ratelimitpolicy/walkthrough/rlp_walkthrough.md
  hack/local-setup.sh
  hack/make/syncer.make
  pkg/_internal/clusterSecret/clusterSecret.go
  pkg/_internal/clusterSecret/service.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/gateway/suite_test.go
  pkg/controllers/ratelimitpolicy/cluster_eventhandler.go
  pkg/controllers/ratelimitpolicy/ratelimitpolicy_controller.go
  pkg/controllers/ratelimitpolicy/suite_test.go
Labels: approved, lgtm

#230 Fix dnspolicy suite_test
  pkg/controllers/dnspolicy/suite_test.go
Labels: approved, lgtm

#227 Multiple dns provider support proposal
  docs/proposals/README.md
  docs/proposals/assets/multiple-dns-provider-support/azure/azure-traffic-manager-request.json
  docs/proposals/assets/multiple-dns-provider-support/azure/azure.md
  docs/proposals/assets/multiple-dns-provider-support/azure/dnsrecord-geo-recordset.png
  docs/proposals/assets/multiple-dns-provider-support/azure/dnsrecord-geo-traffic-manager-profiles.png
  docs/proposals/assets/multiple-dns-provider-support/azure/dnsrecord-geo.azure.hcpapps.net.yaml
  docs/proposals/assets/multiple-dns-provider-support/google/dnsrecord-geo.google.hcpapps.net.yaml
  docs/proposals/assets/multiple-dns-provider-support/google/dnsrecord-weighted.google.hcpapps.net.yaml
  docs/proposals/assets/multiple-dns-provider-support/google/google-a-weighted-request.json
  docs/proposals/assets/multiple-dns-provider-support/google/google-cname-geo-request.json
  docs/proposals/assets/multiple-dns-provider-support/google/google-record-list.png
  docs/proposals/assets/multiple-dns-provider-support/google/google.md
  docs/proposals/multiple-dns-provider-support.md
  docs/proposals/template.md
Labels: approved, lgtm
