Repository Kuadrant/multicluster-gateway-controller, pull requests merged in 2023-11, with the labels that each got.

#635 gh-628 fix deletion of dnsrecord and certificates on deletion of gateway target for dnspolicy and tlspolicy
  pkg/controllers/dnspolicy/dns_helper.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go
  pkg/controllers/dnspolicy/dnspolicy_healthchecks.go
  pkg/controllers/dnspolicy/dnspolicy_healthchecks_test.go
  pkg/controllers/tlspolicy/tlspolicy_certmanager_certificates.go
  pkg/controllers/tlspolicy/tlspolicy_controller.go
  test/integration/dnspolicy_controller_test.go
  test/integration/tlspolicy_controller_test.go
Labels: approved, lgtm

#647 Fix lint errors
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/tlspolicy/tlspolicy_certmanager_certificates.go
Labels: approved, lgtm

#626 Update docs/tlspolicy/tls-policy.md link
  docs/tlspolicy/tls-policy.md
Labels: approved, lgtm

#659 MGC/RLP Walkthrough Updates
  docs/how-to/multicluster-gateways-walkthrough.md
  docs/how-to/simple-ratelimitpolicy-for-app-developers.md
Labels: lgtm

#467 refactor: controller-runtime v0.16.3
  cmd/gateway_controller/main.go
  cmd/policy_controller/main.go
  go.mod
  go.sum
  hack/make/dependencies.make
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/events/cluster_eventmapper.go
  pkg/controllers/events/gateway_eventmapper.go
  pkg/controllers/events/probe_eventmapper.go
  pkg/controllers/gateway/cluster_eventhandler.go
  pkg/controllers/gateway/cluster_eventhandler_test.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/gateway/gateway_controller_test.go
  pkg/controllers/tlspolicy/tlspolicy_controller.go
  pkg/policysync/eventhandler.go
  test/gateway_integration/suite_test.go
  test/policy_integration/suite_test.go
  test/util/helper.go
Labels: enhancement, approved, lgtm, dependencies

#629 Add DNSPolicy Routing Strategy
  bundle/manifests/kuadrant.io_dnspolicies.yaml
  bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml
  config/policy-controller/crd/bases/kuadrant.io_dnspolicies.yaml
  go.mod
  pkg/apis/v1alpha1/dnspolicy_types.go
  pkg/controllers/dnspolicy/dns_helper.go
  pkg/controllers/dnspolicy/dns_helper_test.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go
  test/e2e/gateway_single_spoke_test.go
  test/policy_integration/dnspolicy_controller_test.go
  test/policy_integration/helper_test.go
  test/policy_integration/tlspolicy_controller_test.go
  test/util/test_dnspolicy_types.go
  test/util/test_types.go
Labels: approved, lgtm

#666 Renamed metric services
  config/prometheus/gateway-controller-service.yaml
  config/prometheus/policy-controller-service.yaml
Labels: approved, lgtm

#667 fix perms around issuers
  bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml
  config/add-on-manager/manager.yaml
  config/policy-controller/rbac/role.yaml
  hack/make/policy_controller.make
  pkg/controllers/tlspolicy/tlspolicy_controller.go
  test/e2e/gateway_single_spoke_test.go
Labels: approved, lgtm

#669 Split dnspolicy tests
  test/gateway_integration/suite_test.go
  test/policy_integration/dnspolicy_controller_health_checks_test.go
  test/policy_integration/dnspolicy_controller_multi_cluster_test.go
  test/policy_integration/dnspolicy_controller_single_cluster_test.go
  test/policy_integration/dnspolicy_controller_test.go
  test/policy_integration/suite_test.go
  test/policy_integration/tlspolicy_controller_test.go
Labels: approved, lgtm

#649 remove http check for wildcard certificate in favour of checking certificates
  pkg/apis/v1alpha1/tlspolicy_types.go
  test/e2e/gateway_single_spoke_test.go
  test/util/helper.go
  test/util/test_types.go
Labels: approved, lgtm

#676 Fix docs and remove old manifests from bundle
  bundle/manifests/mgc-kuadrant-dnsrecord-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/mgc-kuadrant-dnsrecord-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  docs/installation/control-plane-installation.md
Labels: approved, lgtm

#638 GH-496 GW target own cluster
  pkg/controllers/dnspolicy/dns_helper.go
  pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/dns/fake/service.go
  pkg/traffic/gateway.go
  pkg/traffic/traffic.go
  pkg/utils/gateway_wrapper.go
  pkg/utils/gateway_wrapper_test.go
  test/policy_integration/dnspolicy_controller_health_checks_test.go
  test/policy_integration/dnspolicy_controller_multi_cluster_test.go
  test/policy_integration/dnspolicy_controller_test.go
Labels: approved, lgtm, tide/merge-method-squash

#677 Freeze docs to v0.1 in release branch
  docs/installation/control-plane-installation.md
  docs/installation/service-protection-installation.md
Labels: approved, lgtm

#684 docs: Add API reference docs for policies
  docs/reference/dnspolicy.md
  docs/reference/tlspolicy.md
Labels: approved, lgtm

#686 update role with managedcluster perms
  bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml
  config/rbac/role.yaml
  pkg/controllers/gateway/gateway_controller.go
Labels: approved, lgtm

#691 Install guide updates
  config/mgc-install-guide/delete-cluster-issuer.yaml
  config/mgc-install-guide/kustomization.yaml
  docs/installation/control-plane-installation.md
  docs/installation/service-protection-installation.md
Labels: approved, lgtm

#695 fix service-protection-installation.md managedclusteraddon annotation
  docs/installation/service-protection-installation.md
Labels: approved, lgtm

#697 minor tidy up
  docs/gateways/define-and-place-a-gateway.md
Labels: approved, lgtm

#688 docs: Add ManagedZone API reference doc
  docs/dnspolicy/dns-provider.md
  docs/dnspolicy/dnspolicy-quickstart.md
  docs/installation/control-plane-installation.md
  docs/managed-zone.md
  docs/reference/managedzone.md
Labels: approved, lgtm

#694 docs: Add DNSPolicy overview doc
  docs/dnspolicy/dns-health-checks.md
  docs/dnspolicy/dnspolicy-quickstart.md
  docs/dnspolicy/dnspolicy.md
  docs/how-to/multicluster-loadbalanced-dnspolicy.md
Labels: approved, lgtm
