Repository Kuadrant/multicluster-gateway-controller, pull requests merged in 2023-10, with the labels that each got.

#607 Update policy status on TargetNotFound
  pkg/_internal/conditions/conditions.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/tlspolicy/tlspolicy_controller.go
  test/integration/dnspolicy_controller_test.go
  test/integration/tlspolicy_controller_test.go
Labels: approved, lgtm

#604 gateway.networking.k8s.io/policy should be a label
  bundle/manifests/kuadrant.io_dnspolicies.yaml
  bundle/manifests/kuadrant.io_tlspolicies.yaml
  config/crd/kustomization.yaml
  config/crd/patches/policy-patch.yaml
Labels: approved, lgtm

#606 Gh 587
  test/integration/dnsheathcheckprobe_controller_test.go
  test/integration/dnspolicy_controller_test.go
  test/integration/tlspolicy_controller_test.go
  test/util/test_types.go
Labels: approved, lgtm

#617 allow channel to be overridden
  cmd/ocm/addon-manager/manifests/subscription.yaml
  cmd/ocm/main.go
Labels: approved, lgtm

#523 Refactor endpoint probe check
  pkg/controllers/dnspolicy/dns_helper.go
  pkg/controllers/dnspolicy/dns_helper_test.go
  pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go
  pkg/dns/target.go
  pkg/dns/target_test.go
Labels: approved, lgtm

#465 GH-311 gateway status instead of ocm api calls
  cmd/controller/main.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go
  pkg/controllers/dnspolicy/dnspolicy_healthchecks_test.go
  test/integration/dnspolicy_controller_test.go
  test/integration/suite_test.go
Labels: approved, lgtm, tide/merge-method-squash

#609 verify wildcard cert on http get request
  test/e2e/gateway_single_spoke_test.go
  test/util/helper.go
  test/util/suite_config.go
  test/util/test_types.go
Labels: approved, lgtm

#621 Watch policies configured by Gateway params
  bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml
  cmd/controller/main.go
  config/quick-start/control-cluster/cluster-config/configmap.yaml
  config/rbac/role.yaml
  pkg/_internal/slice/predicates.go
  pkg/_internal/slice/slice.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/gateway/params.go
  pkg/policysync/eventhandler.go
  pkg/policysync/policy.go
  pkg/policysync/policy_test.go
  pkg/policysync/reflect.go
  pkg/policysync/runnable.go
  pkg/policysync/syncer.go
  pkg/policysync/unstructured.go
Labels: approved, lgtm

#612 RateLimitPolicy guide to follow after gateway walkthrough
  docs/how-to/multicluster-gateways-walkthrough.md
  docs/how-to/simple-ratelimitpolicy-for-app-developers.md
Labels: documentation, approved, lgtm

#632 Add ocp_monitoring sub dir to prometheus-for-federation config
  config/prometheus-for-federation/ocp_monitoring/.gitignore
  config/prometheus-for-federation/ocp_monitoring/README.md
  config/prometheus-for-federation/ocp_monitoring/grafana_datasources.yaml.template
  config/prometheus-for-federation/ocp_monitoring/kustomization.yaml
  config/prometheus-for-federation/ocp_monitoring/monitoring.yaml
Labels: approved, lgtm

#634 Temp workaround for https://github.com/Kuadrant/multicluster-gateway-…
  pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go
Labels: approved

#637 update the default channel to stable for install service protection
  cmd/ocm/main.go
Labels: approved, lgtm
