Repository Kuadrant/multicluster-gateway-controller, pull requests merged in 2023-07, with the labels that each got.

#243 e2e tests
  Makefile
  config/rbac/role.yaml
  go.mod
  go.sum
  hack/make/dependencies.make
  pkg/controllers/gateway/gateway_controller.go
  test/e2e/.gitignore
  test/e2e/gateway_single_spoke_test.go
  test/e2e/suite_test.go
  test/util/echo.go
  test/util/pointer.go
  test/util/suite_config.go
Labels: approved, lgtm

#270 DNSPolicy proposal
  docs/proposals/DNSPolicy.md
  docs/proposals/DNSRecordStructure.md
  docs/proposals/assets/multiple-dns-provider-support/aws/aws-geo-weighted.png
  docs/proposals/assets/multiple-dns-provider-support/aws/aws-weighted.png
  docs/proposals/assets/multiple-dns-provider-support/aws/aws.md
Labels: approved, lgtm

#288 add grace period to descheduled gateways
  hack/make/controller.make
  pkg/_internal/gracePeriod/gracePeriod.go
  pkg/_internal/gracePeriod/gracePeriod_test.go
  pkg/_internal/metadata/annotations.go
  pkg/_internal/policy/policy.go
  pkg/_internal/policy/policy_test.go
  pkg/apis/v1alpha1/dnspolicy_types.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/dns/dns.go
  pkg/dns/service.go
  pkg/placement/ocm.go
  pkg/placement/placement_test.go
Labels: approved, lgtm

#298 Fix gateway status updates
  pkg/_internal/conditions/conditions.go
  pkg/controllers/dnsrecord/dnsrecord_controller.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/gateway/gatewayclass_controller.go
  pkg/controllers/gateway/suite_test.go
  pkg/controllers/managedzone/managedzone_controller.go
  pkg/placement/ocm.go
Labels: approved, lgtm

#301 only run on primary repo
  .github/workflows/stale-closer.yaml
Labels: approved

#293 Geo DNS Strategy
  cmd/controller/main.go
  config/crd/bases/kuadrant.io_dnspolicies.yaml
  docs/proposals/DNSPolicy.md
  go.mod
  go.sum
  pkg/apis/v1alpha1/dnspolicy_types.go
  pkg/apis/v1alpha1/dnsrecord_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/dnspolicy/cluster_eventmapper.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/dnspolicy/dnspolicy_controller_test.go
  pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go
  pkg/controllers/dnspolicy/helper_test.go
  pkg/controllers/dnspolicy/suite_test.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/gateway/suite_test.go
  pkg/controllers/managedzone/suite_test.go
  pkg/dns/aws/dns.go
  pkg/dns/dns.go
  pkg/dns/hostresolv.go
  pkg/dns/iso3166.go
  pkg/dns/service.go
  pkg/dns/service_test.go
  pkg/dns/target.go
  pkg/dns/target_test.go
  pkg/placement/ocm.go
Labels: approved, lgtm

#222 Enable RawFeedbackJsonString feature gate in OCM
  go.mod
  go.sum
  hack/local-setup.sh
  hack/make/dependencies.make
  pkg/placement/ocm.go
  pkg/placement/placement_test.go
Labels: approved, lgtm

#309 Add e2e test to ci
  .github/workflows/ci-e2e.yaml
  .github/workflows/ci.yaml
  Dockerfile
  hack/make/dependencies.make
Labels: approved, lgtm

#316 Add missing rbac
  config/rbac/role.yaml
  hack/make/controller.make
  pkg/controllers/dnspolicy/dnspolicy_controller.go
Labels: approved, lgtm

#312 Add custom weights to DNSPolicy
  Makefile
  config/crd/bases/kuadrant.io_dnspolicies.yaml
  hack/make/check.make
  pkg/_internal/metadata/annotations.go
  pkg/apis/v1alpha1/dnspolicy_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/dns/target.go
  pkg/dns/target_test.go
Labels: approved, lgtm

#318 Improvements/fixes to the E2E CI workflow
  .github/workflows/ci-e2e.yaml
Labels: approved, lgtm

#186 GH-114 increase coverage in gateway package
  pkg/controllers/gateway/cluster_eventhandler_test.go
  pkg/controllers/gateway/gateway_controller_test.go
  pkg/controllers/gateway/gatewayclass_controller_test.go
  pkg/controllers/gateway/params_test.go
  test/mockInterfaces.go
  test/util/helper.go
Labels: approved, lgtm

#313 Update README.md
  README.md
Labels: approved, lgtm

#317 remove m3 folder
  docs/how-to/gateway_deletion.md
Labels: approved, lgtm

#320 dependency pre-req and some associated makefile updates
  README.md
  hack/make/dependencies.make
Labels: approved, lgtm

#321 Fix flaky test
  pkg/controllers/dnspolicy/dnspolicy_controller_test.go
Labels: approved, lgtm

#315 Implement the Gateway status aggregation proposal for addresses and l…
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/gateway/suite_test.go
Labels: approved, lgtm

#326 Domain name crd validation
  config/crd/bases/kuadrant.io_managedzones.yaml
  pkg/apis/v1alpha1/managedzone_types.go
  pkg/controllers/managedzone/suite_test.go
Labels: approved, lgtm

#327 Fix dnsrecord updates
  pkg/controllers/dnsrecord/dnsrecord_controller.go
  pkg/dns/service.go
Labels: approved, lgtm

#332 Fix make fmt
  Makefile
Labels: approved, lgtm

#331 Fix dnsrecord when no addresses in any targets
  pkg/dns/service.go
  pkg/dns/service_test.go
Labels: approved, lgtm

#329 Moved integration test to its package
  Makefile
  pkg/controllers/dnspolicy/suite_test.go
  pkg/controllers/dnsrecord/suite_test.go
  test/integration/dnspolicy_controller_test.go
  test/integration/gateway_controller_test.go
  test/integration/helper_test.go
  test/integration/managedzone_controller_test.go
  test/integration/suite_test.go
Labels: approved, lgtm

#325 Fixing some walkthrough docs
  docs/how-to/ocm-control-plane-walkthrough.md
Labels: approved, lgtm

#283 Gh 228
  .gitignore
  cmd/controller/main.go
  config/crd/bases/kuadrant.io_managedzones.yaml
  config/local-setup/controller/kustomization.yaml
  config/local-setup/controller/managed_zone.yaml
  pkg/apis/v1alpha1/managedzone_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/dnspolicy/dnspolicy_healthchecks.go
  pkg/controllers/dnsrecord/dnsrecord_controller.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/gateway/gateway_controller_test.go
  pkg/controllers/managedzone/managedzone_controller.go
  pkg/dns/aws/dns.go
  pkg/dns/dns.go
  pkg/dns/dnsprovider/dnsProvider.go
  pkg/dns/service.go
  test/integration/dnspolicy_controller_test.go
  test/integration/gateway_controller_test.go
  test/integration/helper_test.go
  test/integration/managedzone_controller_test.go
  test/integration/suite_test.go
  test/mockInterfaces.go
Labels: approved, lgtm

#334 Separate CI jobs for both unit and itegration tests
  .github/workflows/ci.yaml
  Makefile
Labels: good first issue, approved, lgtm

#339 target kuadrant/deployments as a target to update controller image
  .github/workflows/controller-image.yaml
Labels: approved, lgtm

#350 Handle apex domains being used as listener hosts
  pkg/dns/service.go
  pkg/dns/service_test.go
Labels: approved, lgtm

#343 Handle MangedCluster delete events
  pkg/_internal/gracePeriod/gracePeriod.go
  pkg/_internal/gracePeriod/gracePeriod_test.go
  pkg/controllers/dnspolicy/cluster_eventmapper.go
  pkg/placement/ocm.go
Labels: approved, lgtm

#353 s/kudarant/kuadrant/g
  pkg/controllers/gateway/gateway_controller.go
  test/integration/gateway_controller_test.go
Labels: approved, lgtm

#338 Move dns service
  cmd/controller/main.go
  pkg/controllers/dnspolicy/dns_helper.go
  pkg/controllers/dnspolicy/dns_helper_test.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go
  pkg/controllers/dnspolicy/dnspolicy_healthchecks.go
  pkg/controllers/dnsrecord/dnsrecord_controller.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/gateway/gateway_controller_test.go
  pkg/dns/dns.go
  pkg/dns/target.go
  test/e2e/gateway_single_spoke_test.go
  test/integration/gateway_controller_test.go
  test/integration/suite_test.go
  test/mockInterfaces.go
Labels: approved, lgtm

#360 docs: minor typo fixes
  README.md
  docs/how-to/managedZone.md
  docs/how-to/ocm-control-plane-walkthrough.md
  docs/how-to/ratelimiting-shared-redis.md
  docs/how-to/submariner-poc-2-gateways-resiliency-walkthrough.md
  docs/how-to/submariner-poc-hub-gateway-walkthrough.md
  docs/how-to/template.md
  docs/proposals/DNSPolicy.md
  docs/proposals/DNSRecordStructure.md
  docs/proposals/assets/multiple-dns-provider-support/azure/azure.md
  docs/proposals/assets/multiple-dns-provider-support/google/google.md
  docs/proposals/multiple-dns-provider-support.md
  docs/proposals/status-aggregation.md
Labels: approved, lgtm

#365 Add goimports
  .github/workflows/ci.yaml
  Makefile
  cmd/controller/main.go
  cmd/ocm/main.go
  hack/make/check.make
  hack/make/dependencies.make
  hack/verify-imports.sh
  pkg/_internal/gracePeriod/gracePeriod_test.go
  pkg/_internal/metadata/annotations_test.go
  pkg/_internal/metadata/labels_test.go
  pkg/_internal/policy/policy_test.go
  pkg/controllers/dnspolicy/dns_helper.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/gateway/cluster_eventhandler.go
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/gateway/gatewayclass_controller_test.go
  pkg/controllers/managedzone/managedzone_controller.go
  pkg/dns/aws/dns.go
  pkg/dns/aws/health.go
  pkg/dns/aws/metrics.go
  pkg/ocm/hub/addon.go
  pkg/placement/ocm.go
  pkg/placement/placement_test.go
  pkg/tls/service.go
  test/e2e/gateway_single_spoke_test.go
  test/e2e/suite_test.go
  test/integration/gateway_controller_test.go
  test/integration/helper_test.go
  test/integration/managedzone_controller_test.go
  test/integration/suite_test.go
  test/util/suite_config.go
Labels: approved, lgtm

#367 Upgrade cert-manager
  config/cert-manager/kustomization.yaml
Labels: approved, lgtm

#346 Uniform unit tests
  Makefile
  pkg/_internal/gracePeriod/gracePeriod_test.go
  pkg/_internal/metadata/annotations_test.go
  pkg/_internal/metadata/finalizers_test.go
  pkg/_internal/policy/policy_test.go
  pkg/controllers/dnspolicy/dns_helper_test.go
  pkg/controllers/gateway/cluster_eventhandler_test.go
  pkg/controllers/gateway/gateway_controller_test.go
  pkg/controllers/gateway/params_test.go
  pkg/dns/fake/service.go
  pkg/dns/target_test.go
  pkg/placement/fake/ocm.go
  pkg/tls/fake/service.go
  test/integration/dnspolicy_controller_test.go
  test/integration/managedzone_controller_test.go
  test/util/helper.go
Labels: approved, lgtm

#349 Gh 271
  PROJECT
  cmd/controller/main.go
  config/crd/bases/kuadrant.io_dnshealthcheckprobes.yaml
  config/crd/bases/kuadrant.io_dnspolicies.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  docs/proposals/assets/provider-agnostic-dns-health-checks/dnshealthcheckprobe.yaml
  go.mod
  go.sum
  pkg/apis/v1alpha1/dnshealthcheckprobe_types.go
  pkg/apis/v1alpha1/dnspolicy_types.go
  pkg/apis/v1alpha1/health_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/dnshealthcheckprobe/dnshealthcheckprobe_controller.go
  pkg/controllers/dnshealthcheckprobe/notifier.go
  pkg/controllers/dnspolicy/dns_helper.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/dnspolicy/dnspolicy_healthchecks.go
  pkg/health/monitor.go
  pkg/health/probeQueuer.go
  pkg/health/queuedProbeWorker.go
  test/integration/dnsheathcheckprobe_controller_test.go
  test/integration/dnspolicy_controller_test.go
  test/integration/helper_test.go
  test/integration/suite_test.go
Labels: approved, lgtm

#373 Add DNSPolicy docs
  docs/dns-policy.md
  docs/images/dns-policy/aws-recordset-list-1.png
  docs/images/dns-policy/aws-recordset-list-2.png
  docs/images/dns-policy/aws-recordset-list-3.png
  docs/images/dns-policy/aws-recordset-list-4.png
Labels: approved, lgtm

#369 Add metrics scrape configuration for Istio & envoy
  config/prometheus-for-federation/additional-scrape-configs.yaml
  config/prometheus-for-federation/ingress.yaml
  config/prometheus-for-federation/kustomization.yaml
  config/prometheus-for-federation/podmonitor-envoy.yaml
  config/prometheus-for-federation/servicemonitor-istiod.yaml
  docs/how-to/images/metrics-federation-traffic-data-per-pod.png
  docs/how-to/images/metrics-federation-traffic-data.png
  docs/how-to/metrics-federation.md
  hack/local-setup.sh
Labels: approved, lgtm

#379 DNSPolicy improve default behaviour
  docs/dns-policy.md
  docs/how-to/ocm-control-plane-walkthrough.md
  docs/how-to/submariner-poc-2-gateways-resiliency-walkthrough.md
  docs/how-to/submariner-poc-hub-gateway-walkthrough.md
  go.mod
  go.sum
  pkg/controllers/dnspolicy/dns_helper.go
  pkg/controllers/dnspolicy/dns_helper_test.go
  pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go
  pkg/controllers/gateway/gateway_controller.go
  test/e2e/gateway_single_spoke_test.go
  test/integration/dnspolicy_controller_test.go
Labels: approved, lgtm

#384 DNSRecord AWS API Continuous loop
  pkg/controllers/dnsrecord/dnsrecord_controller.go
  pkg/dns/dns.go
  pkg/dns/dns_test.go
Labels: approved, lgtm

#386 Gh 258
  pkg/dns/google/google.go
Labels: needs-rebase

#383 Add thanos datasource to Grafana
  config/grafana/datasources.yaml
  config/grafana/ingress.yaml
  config/grafana/kustomization.yaml
  docs/how-to/images/metrics-federation-traffic-data-grafana.png
  docs/how-to/metrics-federation.md
  hack/local-setup.sh
Labels: approved, lgtm
