Repository Kuadrant/multicluster-gateway-controller, pull requests merged in 2023-09, with the labels that each got.

#469 process all probes
  pkg/health/queuedProbeWorker.go
Labels: approved, lgtm

#466 dns health check doc
  docs/dns-health-checks.md
Labels: approved, lgtm

#470 Scripts and resources for the DNSPolicy demo
  docs/demos/dns-policy/Kuadrant - DNSPolicy (1).png
  docs/demos/dns-policy/Kuadrant - DNSPolicy (2).png
  docs/demos/dns-policy/Kuadrant - DNSPolicy (3).png
  docs/demos/dns-policy/Kuadrant - DNSPolicy.png
  docs/demos/dns-policy/cleanup.sh
  docs/demos/dns-policy/default.png
  docs/demos/dns-policy/dnspolicy-demo.md
  docs/demos/dns-policy/dnspolicy.tape
  docs/demos/dns-policy/resources/dnspolicy_prod-web-default.yaml
  docs/demos/dns-policy/resources/dnspolicy_prod-web-weighted-geo.yaml
  docs/demos/dns-policy/resources/dnspolicy_prod-web-weighted.yaml
  docs/demos/dns-policy/resources/echo-app.yaml
  docs/demos/dns-policy/resources/gateway_prod-web-istio.yaml
  docs/demos/dns-policy/resources/gateway_prod-web.yaml
  docs/demos/dns-policy/resources/managed-cluster-set-binding_gateway-clusters.yaml
  docs/demos/dns-policy/resources/managed-cluster-set_gateway-clusters.yaml
  docs/demos/dns-policy/resources/managedzone_jm.hcpapps.net.yaml
  docs/demos/dns-policy/resources/placement_http-gateway.yaml
  docs/demos/dns-policy/resources/tlspolicy_prod-web.yaml
  docs/demos/dns-policy/script.sh
  docs/demos/dns-policy/weighted-geo-dnschecker.png
  docs/demos/dns-policy/weighted-geo.png
  docs/demos/dns-policy/weighted.png
Labels: approved, lgtm

#473 add doc for configuring dns provider
  config/crd/bases/kuadrant.io_managedzones.yaml
  config/local-setup/controller/aws/managed_zone.yaml
  config/local-setup/controller/gcp/managed_zone.yaml
  docs/dns-policy.md
  docs/how-to/dns-provider.md
  docs/how-to/managedZone.md
  docs/how-to/mgc-setup.md
  docs/how-to/providers/providers.md
  hack/.deployUtils
  pkg/apis/v1alpha1/managedzone_types.go
Labels: approved, lgtm

#477 #474: Use upstream Gateway API repo in guide
  docs/how-to/kuadrant-hub-install.md
Labels: approved, lgtm

#471 Refactor tests to report errors clearly
  test/integration/dnsheathcheckprobe_controller_test.go
  test/integration/dnspolicy_controller_test.go
  test/integration/gateway_controller_test.go
  test/integration/helper_test.go
  test/integration/managedzone_controller_test.go
  test/integration/tlspolicy_controller_test.go
Labels: approved, lgtm

#482 use kubectl config instead of kind context and remove need to clone repo locally
  docs/getting-started.md
  docs/how-to/ocm-control-plane-walkthrough.md
Labels: approved, lgtm

#492 flakey managedzonecontroller test fix
  test/integration/managedzone_controller_test.go
Labels: approved, lgtm

#494 Allow istio operator location to be set
  cmd/ocm/addon-manager/manifests/subscription.yaml
  cmd/ocm/main.go
  cmd/ocm/manifests/subscription.yaml
Labels: approved, lgtm

#495 #472: Add Interval field to DNS Health checks
  config/crd/bases/kuadrant.io_dnspolicies.yaml
  pkg/apis/v1alpha1/dnspolicy_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/dnspolicy/dnspolicy_healthchecks.go
Labels: approved, lgtm

#452 data-plane components installation guide
  config/kuadrant/redis/limitador/kustomization.yaml
  config/service-protection-install-guide/kustomization.yaml
  config/service-protection-install-guide/managed-cluster-addon.yaml
  docs/how-to/kuadrant-hub-install.md
  docs/how-to/ratelimiting-shared-redis.md
  docs/how-to/service-protection-setup.md
Labels: approved, lgtm

#497 format fix
  docs/how-to/ocm-control-plane-walkthrough.md
Labels: approved, lgtm

#412 Delete Endpoint from DNSRecord when endpoint it's related probe is marked with status healthy: false
  Makefile
  cmd/controller/main.go
  pkg/_internal/metadata/labels.go
  pkg/apis/v1alpha1/dnshealthcheckprobe_types.go
  pkg/apis/v1alpha1/dnsrecord_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/dnshealthcheckprobe/dnshealthcheckprobe_controller.go
  pkg/controllers/dnshealthcheckprobe/notifier.go
  pkg/controllers/dnspolicy/dns_helper.go
  pkg/controllers/dnspolicy/dns_helper_test.go
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go
  pkg/controllers/dnspolicy/dnspolicy_healthchecks.go
  pkg/controllers/dnspolicy/dnspolicy_healthchecks_test.go
  pkg/controllers/events/probe_eventmapper.go
  pkg/controllers/gateway/gateway_controller.go
  test/integration/dnsheathcheckprobe_controller_test.go
  test/integration/dnspolicy_controller_test.go
  test/integration/helper_test.go
  test/integration/suite_test.go
Labels: approved, lgtm

#490 #476 - MGC docs re-org
  docs/contribution/contributing.md
  docs/contribution/vscode-debugging.md
  docs/dnspolicy/dns-health-checks.md
  docs/dnspolicy/dns-policy.md
  docs/dnspolicy/dns-provider.md
  docs/dnspolicy/dnspolicy-quickstart.md
  docs/dnspolicy/managed-zone.md
  docs/experimental/skupper-poc-2-gateways-resiliency-walkthrough.md
  docs/experimental/submariner-poc-2-gateways-resiliency-walkthrough.md
  docs/experimental/submariner-poc-hub-gateway-walkthrough.md
  docs/gateways/define-and-place-a-gateway.md
  docs/gateways/gateway-deletion.md
  docs/how-to/metrics-federation.md
  docs/how-to/metrics-walkthrough.md
  docs/how-to/multicluster-gateways-walkthrough.md
  docs/how-to/providers/providers.md
  docs/how-to/ratelimiting-shared-redis.md
  docs/images/metrics/metrics-federation-example-data.png
  docs/images/metrics/metrics-federation-grafana-dashboard-1.png
  docs/images/metrics/metrics-federation-grafana-dashboard-2.png
  docs/images/metrics/metrics-federation-grafana-dashboard-3.png
  docs/images/metrics/metrics-federation-grafana-dashboard-4.png
  docs/images/metrics/metrics-federation-traffic-data-grafana.png
  docs/images/metrics/metrics-federation-traffic-data-per-pod.png
  docs/images/metrics/metrics-federation-traffic-data.png
  docs/images/metrics/metrics-federation.png
  docs/images/skupper/skupper-poc-2-gateways-resiliency-walkthrough.png
  docs/images/submariner/submariner-poc-hub-gateway-diagram.png
  docs/images/vscode/vscode-1.png
  docs/images/vscode/vscode-2.png
  docs/installation/control-plane-installation.md
  docs/installation/service-protection-installation.md
  docs/proposals/DNSPolicy.md
  docs/proposals/multiple-dns-provider-support.md
  docs/tlspolicy/tls-policy.md
Labels: approved, lgtm, mvp, mvp-stretch-goal

#498 fixing some broken image links
  docs/experimental/skupper-poc-2-gateways-resiliency-walkthrough.md
  docs/experimental/submariner-poc-hub-gateway-walkthrough.md
  docs/how-to/metrics-federation.md
  docs/how-to/metrics-walkthrough.md
Labels: approved, lgtm

#491 Gh 276
  .github/workflows/controller-image.yaml
  bundle.Dockerfile
  bundle/manifests/kuadrant.io_dnshealthcheckprobes.yaml
  bundle/manifests/kuadrant.io_dnspolicies.yaml
  bundle/manifests/kuadrant.io_dnsrecords.yaml
  bundle/manifests/kuadrant.io_managedzones.yaml
  bundle/manifests/kuadrant.io_tlspolicies.yaml
  bundle/manifests/mgc-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/mgc-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/multicluster-gateway-controller.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/scorecard/bases/config.yaml
  config/scorecard/kustomization.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  docs/versioning/olm.md
  hack/make/bundle.make
Labels: approved, lgtm

#500 New interval field
  docs/dnspolicy/dns-health-checks.md
Labels: approved, lgtm

#504 fixing some broken links
  docs/getting-started.md
  docs/installation/control-plane-installation.md
Labels: bug, approved, lgtm

#512 Add verify bundle
  .github/workflows/ci.yaml
  bundle/manifests/kuadrant.io_dnspolicies.yaml
  bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml
  hack/make/bundle.make
  hack/make/check.make
Labels: approved, lgtm

#511 quickstart link fix
  hack/quickstart-setup.sh
Labels: bug, approved, lgtm

#499 account for probes relating to multiple listeners
  pkg/controllers/dnspolicy/dns_helper.go
  pkg/controllers/dnspolicy/dns_helper_test.go
  pkg/controllers/dnspolicy/dnspolicy_healthchecks.go
  pkg/controllers/dnspolicy/dnspolicy_healthchecks_test.go
  test/integration/dnspolicy_controller_test.go
  test/integration/helper_test.go
Labels: approved, lgtm

#519 fixing odd formatting on getting-started.md
  docs/getting-started.md
Labels: approved, lgtm

#508 Gh 493 Update docs to include GCP
  docs/getting-started.md
  docs/installation/control-plane-installation.md
Labels: approved, lgtm

#521 Adding GCP to quickstart
  hack/.deployUtils
  hack/.quickstartEnv
  hack/quickstart-setup.sh
Labels: approved, lgtm

#535 Remove duplicate getting started guide in favour of the offical one i…
  docs/gateways/define-and-place-a-gateway.md
  docs/getting-started.md
  docs/how-to/multicluster-gateways-walkthrough.md
  docs/installation/service-protection-installation.md
Labels: approved, lgtm

#539 formatting fixes
  docs/how-to/multicluster-gateways-walkthrough.md
Labels: approved, lgtm

#533 #463: Add gateway.networking.k8s.io/policy annotation
  bundle/manifests/kuadrant.io_dnspolicies.yaml
  bundle/manifests/kuadrant.io_tlspolicies.yaml
  bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml
  config/crd/kustomization.yaml
  config/crd/patches/policy-patch.yaml
Labels: approved, lgtm

#510 Ensure gateway not marked programmed if error with tls secrets
  pkg/controllers/gateway/gateway_controller.go
  pkg/controllers/gateway/gateway_controller_test.go
  test/e2e/gateway_single_spoke_test.go
Labels: approved, lgtm

#550 fix issues in tls policy docs markdown
  docs/tlspolicy/tls-policy.md
Labels: approved

#549 Increase memory limit for mgc
  bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm

#542 Gh 540
  hack/.deployUtils
Labels: approved

#552 fix issues in tls policy docs markdown
  docs/tlspolicy/tls-policy.md
Labels: approved, lgtm

#547 Updating ManagedZone and DNS Provider docs for clarity
  docs/dnspolicy/dns-provider.md
  docs/dnspolicy/managed-zone.md
Labels: approved, lgtm

#554 Fixup few spelling mistakes
  docs/dnspolicy/dns-provider.md
Labels: approved, lgtm

#555 Fixed the links in dns-provider
  docs/dnspolicy/dns-provider.md
Labels: approved, lgtm

#556 Add link to dns provider guide
  docs/installation/control-plane-installation.md
Labels: approved, lgtm

#545 set image pull policy to always
  bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml
  config/add-on-manager/manager.yaml
  config/manager/manager.yaml
Labels: approved, lgtm

#530 Add use case for skupper resiliency
  docs/experimental/skupper-poc-2-gateways-resiliency-walkthrough.md
Labels: approved, lgtm

#557 Fixes #553
  hack/.deployUtils
  hack/.quickstartEnv
  hack/quickstart-setup.sh
Labels: approved

#565 #559 - fixes for the service protection installation guide & multicluster gateway walkthrough
  docs/how-to/multicluster-gateways-walkthrough.md
  docs/installation/service-protection-installation.md
Labels: approved, lgtm

#569 #481: Improve MGC existing clusters guide
  docs/installation/control-plane-installation.md
Labels: documentation, approved, lgtm

#570 Fixes #566 - adds some additional docs around additionalHeadersRef
  docs/dnspolicy/dns-health-checks.md
  docs/dnspolicy/dns-policy.md
Labels: documentation, approved

#575 Fix google dns for records with multiple targets
  pkg/dns/google/google.go
  pkg/dns/google/google_test.go
Labels: approved, lgtm

#572 docs updates
  docs/tlspolicy/tls-policy.md
Labels: approved, lgtm

#580 Gh 561
  .gitignore
  pkg/controllers/dnshealthcheckprobe/dnshealthcheckprobe_controller.go
Labels: approved, lgtm

#584 Update tls docs
  docs/tlspolicy/tls-policy.md
Labels: approved, lgtm

#564 update to doc to make copy and past easier and to add more info
  docs/gateways/define-and-place-a-gateway.md
Labels: approved

#586 Add tlspolicy affected status
  pkg/controllers/dnspolicy/dnspolicy_controller.go
  pkg/controllers/tlspolicy/tlspolicy_controller.go
  test/integration/tlspolicy_controller_test.go
Labels: approved, lgtm

#596 update tests for HTTP expectations with TLS Policy
  test/integration/tlspolicy_controller_test.go
Labels: approved, lgtm

#594 validate the presence of specified issuer or clusterisssuer in tlspolicy
  bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml
  config/rbac/role.yaml
  pkg/controllers/tlspolicy/certmanager_helper.go
  pkg/controllers/tlspolicy/tlspolicy_controller.go
  test/e2e/gateway_single_spoke_test.go
  test/integration/tlspolicy_controller_test.go
  test/util/suite_config.go
  test/util/test_types.go
Labels: approved, lgtm

#593 #574 - addon catalogsource for OpenShift installs
  docs/installation/service-protection-installation.md
Labels: approved

#599 Remove reference to 2nd terminal
  docs/how-to/multicluster-gateways-walkthrough.md
Labels: approved, lgtm

#600 allow source ns to be overridden
  cmd/ocm/addon-manager/manifests/subscription.yaml
  cmd/ocm/main.go
Labels: approved, lgtm

#598 Gateway api state metrics
  config/prometheus-for-federation/grafana_deployment_patch.yaml
  config/prometheus-for-federation/ksm_clusterrole_patch.yaml
  config/prometheus-for-federation/ksm_deployment_patch.yaml
  config/prometheus-for-federation/kustomization.yaml
  docs/how-to/metrics-federation.md
  docs/how-to/metrics-walkthrough.md
  docs/images/metrics/metrics-federation-grafana-dashboard-1.png
  docs/images/metrics/metrics-federation-grafana-dashboard-3.png
  docs/images/metrics/metrics-federation-grafana-dashboard-5.png
  docs/images/metrics/metrics-federation-grafana-dashboard-6.png
  docs/images/metrics/metrics-federation-grafana-dashboard-7.png
  hack/quickstart-metrics.sh
Labels: approved, lgtm
